<?php

use Illuminate\Database\Seeder;

class LeadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('leads')->delete();
        
        \DB::table('leads')->insert(array (
            0 => 
            array (
                'id' => 1,
                'first_name' => 'Nadia',
                'last_name' => 'Sides',
            'phone_primary' => '(595) 897-8912',
            'phone_secondary' => '(738) 288-3349',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Dirt Mining Ltd',
                'title' => 'Director Operations',
                'lead_source' => 'Public Relations',
                'industry' => 1,
                'assigned_to' => 3,
                'employee_count' => 1,
                'address' => '345 Sugar Blvd.',
                'city' => 'Alabama',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'first_name' => 'Mavis',
                'last_name' => 'Loucks',
            'phone_primary' => '(523) 671-7536',
            'phone_secondary' => '(567) 811-4058',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Hammer Group Inc',
                'title' => 'Mgr Operations',
                'lead_source' => 'Conference',
                'industry' => 1,
                'assigned_to' => 5,
                'employee_count' => 1,
                'address' => '67321 West Siam St.',
                'city' => 'St. Petersburg',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'first_name' => 'Sierra',
                'last_name' => 'Finn',
            'phone_primary' => '(096) 281-9021',
            'phone_secondary' => '(272) 616-1814',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => '5D Investments',
                'title' => 'President',
                'lead_source' => '',
                'industry' => 1,
                'assigned_to' => 1,
                'employee_count' => 1,
                'address' => '48920 San Carlos Ave',
                'city' => 'Persistance',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'first_name' => 'Penny',
                'last_name' => 'Strawser',
            'phone_primary' => '(739) 813-4612',
            'phone_secondary' => '(992) 291-8563',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Slender Broadband Inc',
                'title' => 'Mgr Operations',
                'lead_source' => 'Cold Call',
                'industry' => 1,
                'assigned_to' => 1,
                'employee_count' => 1,
                'address' => '48920 San Carlos Ave',
                'city' => 'Salt Lake City',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'first_name' => 'Percy',
                'last_name' => 'Gipe',
            'phone_primary' => '(879) 962-6836',
            'phone_secondary' => '(998) 926-0660',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Union Bank',
                'title' => 'VP Operations',
                'lead_source' => 'Partner',
                'industry' => 1,
                'assigned_to' => 6,
                'employee_count' => 1,
                'address' => '9 IBM Path',
                'city' => 'Sunnyvale',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'first_name' => 'Isaac',
                'last_name' => 'Tusing',
            'phone_primary' => '(244) 175-9420',
            'phone_secondary' => '(798) 635-5483',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Kings Royalty Trust',
                'title' => 'VP Sales',
                'lead_source' => 'Partner',
                'industry' => 1,
                'assigned_to' => 6,
                'employee_count' => 1,
                'address' => '67321 West Siam St.',
                'city' => 'Santa Monica',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'first_name' => 'Wyatt',
                'last_name' => 'Muro',
            'phone_primary' => '(399) 281-8144',
            'phone_secondary' => '(374) 136-8960',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Complete Holding',
                'title' => 'Mgr Operations',
                'lead_source' => 'Direct Mail',
                'industry' => 1,
                'assigned_to' => 3,
                'employee_count' => 1,
                'address' => '9 IBM Path',
                'city' => 'Kansas City',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'first_name' => 'Bonita',
                'last_name' => 'Cowden',
            'phone_primary' => '(268) 132-7858',
            'phone_secondary' => '(252) 008-9393',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'JAB Funds Ltd.',
                'title' => 'VP Sales',
                'lead_source' => 'Self Generated',
                'industry' => 1,
                'assigned_to' => 5,
                'employee_count' => 1,
                'address' => '9 IBM Path',
                'city' => 'Denver',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'first_name' => 'Vilma',
                'last_name' => 'Ellingson',
            'phone_primary' => '(744) 348-1383',
            'phone_secondary' => '(541) 491-9537',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Hollywood Diner Ltd',
                'title' => 'Senior Product Manager',
                'lead_source' => 'Other',
                'industry' => 1,
                'assigned_to' => 6,
                'employee_count' => 1,
                'address' => '1715 Scott Dr',
                'city' => 'Denver',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'first_name' => 'Hugo',
                'last_name' => 'Hummell',
            'phone_primary' => '(540) 845-2470',
            'phone_secondary' => '(601) 993-5342',
                'email_primary' => '',
                'email_secondary' => '',
                'company' => 'Nelson Inc',
                'title' => 'President',
                'lead_source' => 'Word of mouth',
                'industry' => 1,
                'assigned_to' => 5,
                'employee_count' => 1,
                'address' => '123 Anywhere Street',
                'city' => 'Santa Monica',
                'country' => 'USA',
                'description' => '',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}